### ISSUE TITLE
What is "opt.times" for?

### ISSUE THREAD

**Issue by JeremyCJM** [mingyuan-zhang/MotionDiffuse#12]
Hi Mingyuan, 

What is "opt.times" for? I see it is multiplied on the real dataset length in __len__() method, why do this? Why not just increase the epoch number?

Thanks,
Jeremy

**Comment by mingyuan-zhang** [comment]
> Hi Mingyuan,
> 
> What is "opt.times" for? I see it is multiplied on the real dataset length in **len**() method, why do this? Why not just increase the epoch number?
> 
> Thanks, Jeremy

Initializing dataloader costs much time because it needs to build datasets for each worker. Therefore I just duplicate the dataset several times to reduce the number of dataloader initialization.

However, the usage of [`persistent_worker`](https://github.com/mingyuan-zhang/MotionDiffuse/blob/d47744809253c9f0164a5a88eac265051e404715/text2motion/datasets/dataloader.py#L64) in the dataloader can significantly relief this situation. `opt.times` is then not necessary for current code.

**Comment by JeremyCJM** [comment]
I see, thanks.
